version: '3.1'

services:

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    networks:
      - net

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: user@mail.com
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - 5050:80
    networks:
      - net

  redis:
    image: redis:latest
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    networks:
      - net

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    restart: unless-stopped
    ports:
      - 8082:80
    environment:
      REDIS_1_HOST: redis
      REDIS_1_PORT: 6379
    networks:
      - net

networks:
  net:
    driver: bridge
